//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Decreption { get; set; }
        public string Title { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Article_Type { get; set; }
        public string Price { get; set; }
        public string PhoneNumber { get; set; }
        public string Create_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CardId { get; set; }
        public string UserNameFree { get; set; }
        public string EmailFree { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> CustommerId { get; set; }
        public Nullable<int> DistrictId { get; set; }
    }
}
