//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Free
    {
        public int Id { get; set; }
        public string Article_Content { get; set; }
        public Nullable<int> Article_ImgId { get; set; }
        public Nullable<int> Article_ProvinceId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
