//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên danh mục không được để trống")]
        public string Name { get; set; }
        public string Status { get; set; }
        [Required(ErrorMessage = "Thứ tự không được để trống")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Chỉ nhập số")]
        public Nullable<int> CategoryId { get; set; }
    }
}
