//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Free_Article
    {
        public int Id { get; set; }
        public string Decreption { get; set; }
        public string Title { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CustommerId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Free_Article_Id { get; set; }
        public string Status { get; set; }
    }
}
