//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> Parent_Id { get; set; }
    }
}
