//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADS.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string StaffType { get; set; }
        public string Status { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> ProvinceId { get; set; }
    }
}
